/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MealsRouteImport } from './routes/meals'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HelpRouteImport } from './routes/help'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ApiPaymentWebhookRouteImport } from './routes/api/payment-webhook'
import { Route as AdminWebhooksRouteImport } from './routes/admin.webhooks'
import { Route as AdminUsersRouteImport } from './routes/admin.users'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsRoute = MealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPaymentWebhookRoute = ApiPaymentWebhookRouteImport.update({
  id: '/api/payment-webhook',
  path: '/api/payment-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebhooksRoute = AdminWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/meals': typeof MealsRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/sales': typeof SalesRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/api/payment-webhook': typeof ApiPaymentWebhookRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/meals': typeof MealsRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/sales': typeof SalesRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/api/payment-webhook': typeof ApiPaymentWebhookRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/meals': typeof MealsRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/sales': typeof SalesRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/api/payment-webhook': typeof ApiPaymentWebhookRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/help'
    | '/home'
    | '/login'
    | '/meals'
    | '/notifications'
    | '/pricing'
    | '/profile'
    | '/sales'
    | '/scan'
    | '/settings'
    | '/admin/users'
    | '/admin/webhooks'
    | '/api/payment-webhook'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/help'
    | '/home'
    | '/login'
    | '/meals'
    | '/notifications'
    | '/pricing'
    | '/profile'
    | '/sales'
    | '/scan'
    | '/settings'
    | '/admin/users'
    | '/admin/webhooks'
    | '/api/payment-webhook'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/help'
    | '/home'
    | '/login'
    | '/meals'
    | '/notifications'
    | '/pricing'
    | '/profile'
    | '/sales'
    | '/scan'
    | '/settings'
    | '/admin/users'
    | '/admin/webhooks'
    | '/api/payment-webhook'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  HelpRoute: typeof HelpRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  MealsRoute: typeof MealsRoute
  NotificationsRoute: typeof NotificationsRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  SalesRoute: typeof SalesRoute
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  ApiPaymentWebhookRoute: typeof ApiPaymentWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals': {
      id: '/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof MealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/payment-webhook': {
      id: '/api/payment-webhook'
      path: '/api/payment-webhook'
      fullPath: '/api/payment-webhook'
      preLoaderRoute: typeof ApiPaymentWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/webhooks': {
      id: '/admin/webhooks'
      path: '/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AdminWebhooksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWebhooksRoute: typeof AdminWebhooksRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsersRoute: AdminUsersRoute,
  AdminWebhooksRoute: AdminWebhooksRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  HelpRoute: HelpRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  MealsRoute: MealsRoute,
  NotificationsRoute: NotificationsRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  SalesRoute: SalesRoute,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  ApiPaymentWebhookRoute: ApiPaymentWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
